### PR TITLE
Upgrade versions in setup.py

### LINKED ISSUE #1333: ReadTheDocs build failed
From ReadTheDocs email:

    --snip--
    Installed /home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.11/site-packages/cachelib-0.9.0-py3.11.egg
    error: Jinja2 2.11.3 is installed but Jinja2<4.0.0,>=3.1.2 is required by {'Flask-Babel'}

Ran `m extras` to install scrips needed to reproduce problem locally:

    --snip--
    ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
    flask 1.1.4 requires Jinja2<3.0,>=2.10.1, but you have jinja2 3.1.2 which is incompatible.
    moin 2.0.0a12.dev76+gcc8fc0a7.d20230116 requires docutils<0.18, but you have docutils 0.19 which is incompatible.
    moin 2.0.0a12.dev76+gcc8fc0a7.d20230116 requires Jinja2<3.0.0, but you have jinja2 3.1.2 which is incompatible.

Ran `m docs` to build local docs, seems successful with a few warnings:

    --snip--
    Running Sphinx v6.1.3
    WARNING: logo file 'Logo_MoinMoin.png' does not exist
    WARNING: favicon file 'favicon.ico' does not exist
    loading pickled environment... failed
    failed: Can't get attribute '_stable_repr_object' on <sphinx.deprecation._ModuleWrapper object at 0x0000014D759437F0>

Tried to start server to view local docs:

    (moin-venv-python) C:\git\moin>m run
    Traceback (most recent call last):
      File "C:\GIT\moin-venv-python\Scripts\moin-script.py", line 33, in <module>
        sys.exit(load_entry_point('moin', 'console_scripts', 'moin')())
      File "C:\GIT\moin-venv-python\Scripts\moin-script.py", line 25, in importlib_load_entry_point
        return next(matches).load()
      File "C:\Users\haase\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 171, in load
        module = import_module(match.group('module'))
      File "C:\Users\haase\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "c:\git\moin\src\moin\scripts\__init__.py", line 11, in <module>
        from flask_script import Manager, Server, Command
      File "C:\GIT\moin-venv-python\lib\site-packages\flask_script\__init__.py", line 14, in <module>
        from flask import Flask
      File "C:\GIT\moin-venv-python\lib\site-packages\flask\__init__.py", line 14, in <module>
        from jinja2 import escape
    ImportError: cannot import name 'escape' from 'jinja2' (C:\GIT\moin-venv-python\lib\site-packages\jinja2\__init__.py)

Downgraded jinja2 and docutils:

    pip install jinja2==2.11.3
    pip install docutils==0.17.1

Server stars successfully, local docs are OK

### PR DESCRIPTION
**Pull request by UlrichB22**
Change dependencies to upgrade to newer versions as discussed in #1109

- Flask                         2.0.3
- Flask-Script               2.0.5
- Jinja2                        3.0.3
- MarkupSafe               2.1.2
- Werkzeug                   2.1.2

Hopefully it also fixes #1333, my tests with `./m docs` run successfully in Debian 11.

Please support with testing in different environments.

### CODE REVIEW

**Comment by RogerHaase** [comment]
Works on Windows 10 with Python 3.10. But a freshly created venv still has sphinx-rtd-theme version 0.5.1 even though docs/requirements says "sphinx-rtd-theme==1.1.1".

Still fails on readthedocs with "sphinx-rtd-theme==1.1.1 ". See https://github.com/readthedocs/sphinx_rtd_theme/issues/1323

"""
python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
Collecting docutils>=0.18.1
  Downloading docutils-0.19-py3-none-any.whl (570 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.5/570.5 kB 44.3 MB/s eta 0:00:00
Collecting sphinx>=5.3.0
  Downloading sphinx-6.1.3-py3-none-any.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 122.4 MB/s eta 0:00:00
Collecting sphinx-rtd-theme==1.1.1
  Downloading sphinx_rtd_theme-1.1.1-py2.py3-none-any.whl (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 217.5 MB/s eta 0:00:00
Collecting sphinx>=5.3.0
  Downloading sphinx-5.3.0-py3-none-any.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 229.5 MB/s eta 0:00:00
ERROR: Cannot install -r docs/requirements.txt (line 4) and docutils>=0.18.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested docutils>=0.18.1
    sphinx-rtd-theme 1.1.1 depends on docutils<0.18

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
"""

Upgrading sphinx to 1.1.1 fails. Upgrading sphinx-rtd-theme to 1.2.0rc3 Succeeds,

**Comment by UlrichB22** [comment]
Is it ok to temporarily pin sphinx-rtd-theme to 1.2.0rc3 in requirements.txt? 
Version 1.2.0 seems to be coming soon.

**Comment by RogerHaase** [comment]
Yes, but installing sphinx-rtd-theme to 1.2.0rc3 still downgrades docutils to 18.1.

I am thinking it is time to find another theme. The theme was changed from classic to sphinx-rtd-theme on 2016-02-03: cf48fcc1bccc7629747e9c774bd226e45c720589 because it had better support for smartphone screen sizes.
